name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-check:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      new_version: ${{ steps.check.outputs.new_version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check the version
        id: check
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          echo "Current version: $CURRENT_VERSION"
          LATEST_VERSION=$(npm view dreamland versions --json | jq -r '.[-1]' || echo "0.0.0")
          echo "Latest NPM version: $LATEST_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ];
          then
            echo "Version changed"
            echo "version_changed=true" >> "$GITHUB_OUTPUT"
            echo "new_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "Version not changed"
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
          fi
  build:
    name: Build Dreamland
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Pack Dreamland
        run: pnpm pack

      - name: Upload Artifact (pnpm pack)
        uses: actions/upload-artifact@v4
        with:
          name: packaged-dreamland
          path: dreamland-*.tgz

      - name: Upload Artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: dreamland
          path: |
            dist/*.d.ts
            dist/*.js
            dist/*.js.map
    
  publish:
    name: Publish Dreamland to NPM
    runs-on: ubuntu-latest
    needs: [version-check, build]
    permissions: write-all
    if: ${{ github.ref == 'refs/heads/rewrite' }} && ${{ needs.version-check.outputs.version_changed == 'true' }}

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: packaged-dreamland
          path: .

      - name: Publish
        run: npm publish dreamland-${{ needs.version-check.outputs.new_version }}.tgz --access public --no-git-checks

  deploy:
    name: Upload to Github Pages
    runs-on: ubuntu-latest
    needs: [version-check, build]
    permissions: write-all
    if: github.ref == 'refs/heads/rewrite'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: dreamland
          path: dist

      - name: Install site deps
        run: pnpm i
        working-directory: "./site"

      - name: Build site
        run: pnpm build
        working-directory: "./site"

      - name: Add 404.html
        run: cp ./site/dist/static/index.html ./site/dist/static/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./site/dist/static"
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4